# Generated by Django 3.2.5 on 2021-08-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_uploads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
