# Generated by Django 3.2.5 on 2021-08-08 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_homeworkuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkuploads',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 15, 39, 31, 476374)),
        ),
        migrations.AlterField(
            model_name='homeworkuploads',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
