# Generated by Django 3.2.5 on 2021-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_homeworkuploads_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkuploads',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
