# Generated by Django 3.2.5 on 2021-08-14 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notifications')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2021, 8, 14, 10, 21, 45, 641706, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='chat',
        ),
    ]
