# Generated by Django 3.2.5 on 2021-08-14 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20210814_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 14, 14, 13, 26, 933133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 14, 14, 13, 26, 933133, tzinfo=utc)),
        ),
    ]
