# Generated by Django 3.2.5 on 2021-08-29 11:34

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20210814_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkuploads',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 11, 34, 20, 30670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 11, 34, 20, 30670, tzinfo=utc)),
        ),
    ]
