# Generated by Django 3.2.5 on 2021-09-03 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20210829_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=200)),
                ('writter', models.CharField(max_length=200)),
                ('aurhor', models.ImageField(upload_to='motivation')),
                ('date', models.DateField(default=datetime.datetime(2021, 9, 3, 12, 56, 22, 313603, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Motivation',
        ),
        migrations.AlterField(
            model_name='homeworkuploads',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 12, 56, 22, 313603, tzinfo=utc)),
        ),
    ]
