# Generated by Django 3.2.5 on 2021-09-03 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20210903_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='color',
            field=models.CharField(default=datetime.datetime(2021, 9, 3, 12, 58, 46, 974738, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 12, 58, 34, 732317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 12, 58, 34, 732317, tzinfo=utc)),
        ),
    ]
