# Generated by Django 3.2.5 on 2021-09-04 09:11

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20210903_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='questions')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 9, 11, 16, 78742, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 9, 11, 16, 78742, tzinfo=utc)),
        ),
    ]
