# Generated by Django 3.2.5 on 2021-09-04 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20210904_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 9, 11, 55, 806010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 9, 11, 55, 821635, tzinfo=utc)),
        ),
    ]
