# Generated by Django 3.2.5 on 2021-09-04 12:57

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20210904_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('files', models.FileField(upload_to='notes')),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 12, 57, 48, 526667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 12, 57, 48, 526667, tzinfo=utc)),
        ),
    ]
